name: Chat app
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Run
      run: |
        echo "Run 'build' job"
        
    - name: Complete with failure
      run: |
        echo "Completed 'build' job, but triggering failure"
        exit 1

  notify:
    runs-on: ubuntu-latest
    if: ${{ always() }}
    needs: [build]
    env:
      WEBHOOK: ${{ secrets.DISCORD }}
      AVATAR_URL: https://avatars.githubusercontent.com/u/29285980?s=400&u=e6644c135c541ef80b39bea82b09ffef175a2a52&v=4
    
    steps:
    - name: Test Success
      if: ${{ contains(needs.*.result, 'success') }}
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: info
          details: Build Succeeded!
          webhookUrl: ${{ env.WEBHOOK }}
          avatarUrl: ${{ env.AVATAR_URL }}
    
    - name: Test Failure
      if: ${{ contains(needs.*.result, 'failure') }}
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: error
          details: Build Failed!
          webhookUrl: ${{ env.WEBHOOK }}
          avatarUrl: ${{ env.AVATAR_URL }}

    - name: Test Cancelled
      if: ${{ contains(needs.*.result, 'cancelled') }}
      uses: rjstone/discord-webhook-notify@v1
      with:
          severity: warn
          details: Build Cancelled!
          webhookUrl: ${{ env.WEBHOOK }}
          avatarUrl: ${{ env.AVATAR_URL }}
